M48
; DRILL file {KiCad (6.0.7)} date Thu Feb  2 22:14:04 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-02T22:14:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.6106Y-5.7441
X4.8382Y-5.7441
T2
X3.6614Y-4.0551
X3.6614Y-5.8661
X5.7874Y-4.0551
X5.7874Y-5.8661
T0
M30
